---

- name: autodetect | Detectar o mecanismo de virtualização
  block:
    - name: autodetect | Carregar o módulo do kernel KVM
      modprobe:
        name: kvm
      failed_when: false

    - name: autodetect | Verificar se o módulo KVM está ativo
      stat:
        path: /dev/kvm
      register: stat_kvm

    # As instruções de virtualização geralmente estão disponíveis apenas para a 
    # arquitetura do host. Idealmente, testaríamos as instruções de virtualização, 
    # por exemplo. vt-d, uma vez que é possível que outra arquitetura possa ser 
    # suportada, mesmo que a arquitetura da cpu emulada não seja a mesma.
    - name: autodetect | Registrar o melhor mecanismo a ser utilizado
      set_fact:
        vm_base_engine: >-
          {%- if ansible_architecture != vm_base_arch -%}
          qemu
          {%- elif stat_kvm.stat.exists -%}
          kvm
          {%- else -%}
          qemu
          {%- endif -%}
  when: vm_base_engine is none

- name: autodetect | Detectar o emulador de virtualização
  block:
    - block:
        - name: autodetect | Detectar o caminho binário do emulador KVM
          stat:
            path: "{{ item }}"
          register: kvm_emulator_result
          with_items:
            - /usr/bin/kvm
            - /usr/bin/qemu-kvm
            - /usr/libexec/qemu-kvm

        - name: autodetect | Registrar o caminho binário do emulador KVM
          set_fact:
            vm_base_emulator: "{{ item.item }}"
          with_items: "{{ kvm_emulator_result.results }}"
          when: item.stat.exists
      when: vm_base_engine == 'kvm'

    - block:
        - name: autodetect | Detectar o caminho binário do emulador QEMU
          shell: which qemu-system-{{ vm_base_arch }}
          register: qemu_emulator_result
          changed_when: false

        - name: autodetect | Registrar o caminho binário do emulador QEMU
          set_fact:
            vm_base_emulator: "{{ qemu_emulator_result.stdout }}"
      when: vm_base_engine == 'qemu'

    - name: autodetect | Falhar se não for possível detectar o emulador
      fail:
        msg: Não é possível detectar o emulador para o mecanismo {{ vm_base_engine }}.
      when: vm_base_emulator is none
  when: vm_base_emulator is none
