---

- name: clean | Destruir VM Base anterior
  virt: 
    state: destroyed
    name: "{{ vm_base.name }}"

- name: clean | Remover storages da VM Base anterior
  command: "virsh --connect qemu:///system undefine {{ vm_base.name }} --remove-all-storage"

- name: clean | Remover VM Base do known_hosts
  lineinfile:
    path: "~/.ssh/known_hosts"
    state: absent
    regexp: "{{item}}"
  become: false
  with_items:
    - "{{ vm_base_network.domain }}"
    - "{{ vm_base_network.addresses[0].split('.')[0:3] | join('.') }}"