---
- name: prelude | Coletar as variáveis especificas para do sistema
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - skip: True

- name: prelude | Verificar se a VM Base existe
  virt:
    name: "{{ vm_base.name }}"
    command: list_vms
  register: vm_base_info
