---
- name: Instalando pacotes de virtualização
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - virt-manager
    - virt-install
    - virt-top
    - libvirt
    - libvirt-python
    - python-lxml
    - python3-netaddr
  delegate_to: "{{ libvirt__install_host }}"

- name: Gerando o arquivo libvirt.conf
  template:
    src: 'root/etc/libvirt/libvirt.conf.j2'
    dest: '/etc/libvirt/libvirt.conf'
  delegate_to: "{{ libvirt__install_host }}"

- name: Start/Enable libvirtd
  systemd: 
    name: libvirtd 
    enabled: yes 
    state: started
  delegate_to: "{{ libvirt__install_host }}"
