---
- name: Instalação e Configuração do KVM
  hosts: localhost
  become: True
  tags: kvm
  roles: 
    - kvm

- name: Provisionar VM Base para o Cluster
  hosts: localhost
  become: True
  tags: vm-base
  roles: 
    - vm-base