---

- name: Instalar docker
  yum:
    name: "docker-{{ okd_docker_version }}"
    state: present
  register: rpm_install
  async: 500
  poll: 0

- name: Aguardar pela instalação do docker
  async_status: jid="{{ rpm_install.ansible_job_id }}"
  become: yes
  register: jobs
  until: jobs.finished
  retries: 50
  delay: 10

- name: Configure docker-storage-setup configuration
  copy:
    content: |
      STORAGE_DRIVER=overlay2
      CONTAINER_ROOT_LV_NAME=dockerlv
      CONTAINER_ROOT_LV_SIZE=100%FREE
      CONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker
      DEVS=/dev/{{ okd_docker_storage_disk }}
      VG=docker-vg
      EXTRA_STORAGE_OPTIONS="--storage-opt overlay2.size=3G"
    dest: /etc/sysconfig/docker-storage-setup
  when: jobs.finished

- name: Run docker-storage-setup
  command: docker-storage-setup
  when: jobs.finished

- name: Start and enable docker
  systemd:
    name: docker
    enabled: yes
    state: started
  when: jobs.finished
