---

- include: clean.yml
  when: okd_recreate

- name: Realizando o deploy para a VM de LOADBALANCE
  include: deploy.yml
  vars:
    clone_src: "{{ vm_base_machine.name }}"
    clone_dest: "{{ okd_prefix }}-{{ vm_lbs.prefix }}{% if vm_lbs.vms > 1 %}-{{ num }}{% else %}{% endif %}"
    clone_fqdn: "{{ vm_lbs.prefix }}{% if vm_lbs.vms > 1 %}{{ num }}{% else %}{% endif %}.{{ vm_base_network.domain }}"
    clone_memory: "{{ vm_lbs.memory }}"
    clone_vcpus: "{{ vm_lbs.vcpus }}"
  loop: "{{ range(1,vm_lbs.vms|int + 1,1)|list }}"
  loop_control:
    loop_var: num
  when: vm_lbs is defined and vm_lbs.vms|int > 0 

- name: Realizando o deploy para as VMs MASTERS
  include: deploy.yml
  vars:
    clone_src: "{{ vm_base_machine.name }}"
    clone_dest: "{{ okd_prefix }}-{{ vm_masters.prefix }}{% if vm_masters.vms > 1 %}-{{ num }}{% else %}{% endif %}"
    clone_fqdn: "{{ vm_masters.prefix }}{% if vm_masters.vms > 1 %}{{ num }}{% else %}{% endif %}.{{ vm_base_network.domain }}"
    clone_memory: "{{ vm_masters.memory }}"
    clone_vcpus: "{{ vm_masters.vcpus }}"
  loop: "{{ range(1,vm_masters.vms|int + 1,1)|list }}"
  loop_control:
    loop_var: num
  when: vm_masters is defined and vm_masters.vms|int > 0  

- name: Realizando o deploy para as VMs INFRAS
  include: deploy.yml
  vars:
    clone_src: "{{ vm_base_machine.name }}"
    clone_dest: "{{ okd_prefix }}-{{ vm_infras.prefix }}{% if vm_infras.vms > 1 %}-{{ num }}{% else %}{% endif %}"
    clone_fqdn: "{{ vm_infras.prefix }}{% if vm_infras.vms > 1 %}{{ num }}{% else %}{% endif %}.{{ vm_base_network.domain }}"
    clone_memory: "{{ vm_infras.memory }}"
    clone_vcpus: "{{ vm_infras.vcpus }}"
  loop: "{{ range(1,vm_infras.vms|int + 1,1)|list }}"
  loop_control:
    loop_var: num
  when: vm_infras is defined and vm_infras.vms|int > 0  

- name: Realizando o deploy para as VMs APPS
  include: deploy.yml
  vars:
    clone_src: "{{ vm_base_machine.name }}"
    clone_dest: "{{ okd_prefix }}-{{ vm_apps.prefix }}{% if vm_apps.vms > 1 %}-{{ num }}{% else %}{% endif %}"
    clone_fqdn: "{{ vm_apps.prefix }}{% if vm_apps.vms > 1 %}{{ num }}{% else %}{% endif %}.{{ vm_base_network.domain }}"
    clone_memory: "{{ vm_apps.memory }}"
    clone_vcpus: "{{ vm_apps.vcpus }}"
  loop: "{{ range(1,vm_apps.vms|int + 1,1)|list }}"
  loop_control:
    loop_var: num
  when: vm_apps is defined and vm_apps.vms|int > 0  

- name: Adicionando o docker storage para as VMs MASTERS
  include: storage.yml
  vars:
    storage_dest: "{{ okd_prefix }}-{{ vm_masters.prefix }}{% if vm_masters.vms > 1 %}-{{ num }}{% else %}{% endif %}"
    storage_size: "{{ okd_docker_storage_size }}"
    storage_type: "{{ okd_docker_storage_disk }}"
  loop: "{{ range(1,vm_masters.vms|int + 1,1)|list }}"
  loop_control:
    loop_var: num
  when: vm_masters is defined and vm_masters.vms|int > 0  

- name: Adicionando o docker storage para as VMs INFRAS
  include: storage.yml
  vars:
    storage_dest: "{{ okd_prefix }}-{{ vm_infras.prefix }}{% if vm_infras.vms > 1 %}-{{ num }}{% else %}{% endif %}"
    storage_size: "{{ okd_docker_storage_size }}"
    storage_type: "{{ okd_docker_storage_disk }}"
  loop: "{{ range(1,vm_infras.vms|int + 1,1)|list }}"
  loop_control:
    loop_var: num
  when: vm_infras is defined and vm_infras.vms|int > 0  

- name: Adicionando o docker storage para as VMs APPS
  include: storage.yml
  vars:
    storage_dest: "{{ okd_prefix }}-{{ vm_apps.prefix }}{% if vm_apps.vms > 1 %}-{{ num }}{% else %}{% endif %}"
    storage_size: "{{ okd_docker_storage_size }}"
    storage_type: "{{ okd_docker_storage_disk }}"
  loop: "{{ range(1,vm_apps.vms|int + 1,1)|list }}"
  loop_control:
    loop_var: num
  when: vm_apps is defined and vm_apps.vms|int > 0  
