---

- name: clean | Destruir VM Base anterior
  virt: 
    state: destroyed
    name: "{{ vm_base.name }}"

- name: clean | Remover storages da VM Base anterior
  command: "virsh --connect qemu:///system undefine {{ vm_base.name }} --remove-all-storage"

- name: clean | Remover VM Base do known_hosts
  lineinfile:
    path: "~/.ssh/known_hosts"
    state: absent
    regexp: "{{item}}"
  become: false
  with_items:
    - "example.com"
    - "192.168.200"