---

- name: Assegurar que a VM esta definida
  virt:
    name: "{{ vm_base.name }}"
    command: define
    xml: "{{ lookup('template', 'cloud-init/vm-template.xml.j2') }}"

- name: Iniciando a VM no KVM
  virt:
    name: "{{ vm_base.name }}"
    autostart: "{{ vm_base.autostart | d('True') }}"
    state: "{{ 'running' if (start | d('True')) else 'shutdown' }}"

- name: Capturando o endereço MAC da VM
  shell: >
     virsh --connect qemu:///system dumpxml {{ vm_base.name }} | awk -F\' '/mac address/ {print $2}'
  register: mac_info

- name: Aguardando conexão com a VM
  wait_for:
    path: "/var/lib/libvirt/dnsmasq/virbr1.status"
    search_regex: "{{ mac_info.stdout }}"

- name: Capturando o endereço IP da VM
  shell: >
     grep -B1 {{ mac_info.stdout }} /var/lib/libvirt/dnsmasq/virbr1.status | head -n 1 | awk '{print $2}' | sed -e s/\"//g -e s/,//
  register: vm_ip

- name: Ejetando o cd-rom da VM
  shell: "virsh --connect qemu:///system change-media {{ vm_base.name }} sda --eject --config"

- name: Incluindo o IP da VM no known_hosts
  shell: "ssh-keyscan -t rsa {{ vm_ip.stdout }}  >> ~/.ssh/known_hosts"
  become: false
  ignore_errors: yes
  register: add_known_host
  until: "add_known_host is succeeded and not add_known_host.stderr.find('refused') != -1"
  retries: 180
  delay: 5

- name: Removendo o endereço MAC da eth0 na VM
  shell: "ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ vm_ip.stdout }} -- sudo sed '/HWADDR/d'  -i /etc/sysconfig/network-scripts/ifcfg-eth0"
  ignore_errors: yes
  become: false
  register: remove_mac
  until: remove_mac is succeeded
  retries: 180
  delay: 5

- name: Refresh inventory to ensure new instaces exist in inventory
  meta: refresh_inventory

- name: Atualizando a VM Base
  block:
    - name: Atualizando todos os pacotes
      yum:
        name: '*'
        state: latest
      become: yes
      register: rpm_upgrade
      async: 1800
      poll: 0
    
    - name: Aguardando pela atualização da VM Base
      async_status: jid="{{ rpm_upgrade.ansible_job_id }}"
      become: yes
      register: jobs
      until: jobs.finished
      retries: 180
      delay: 10
    
    - name: Limpando os pacotes
      shell: yum clean all; yum repolist
      
    - name: Reiniciando a VM
      reboot:    
      become: yes
  delegate_to: "{{ vm_ip.stdout }}" 