---
- include: prelude.yml

- include: network.yml
  vars:
    network: "{{ vm_base_network }}"

- include: pool.yml
  vars:
    pool: "{{ vm_base_machine.pool }}"

- include: autodetect.yml

- include: download.yml

- include: cloud-init.yml
  vars:
    network: "{{ vm_base_network }}"
    pool: "{{ vm_base_machine.pool }}"
    volumes: "{{ vm_base_machine.volumes }}"

- include: deploy.yml
  vars:
    vm_base: "{{ vm_base_machine }}"
    volumes: "{{ vm_base_machine.volumes }}"
    pool: "{{ vm_base_machine.pool }}"
    machine_default: "{{ none if vm_base_engine == 'kvm' else 'pc-1.0' }}"
