---
- name: Certificar que o diret칩rio existe
  file:
    path: "{{ pool.path }}/{{ pool.name }}"
    owner: "{{ pool.owner | d('root') }}"
    group: "{{ pool.group | d('root') }}"
    mode: "{{ pool.mode | d('0655')  }}"
    state: directory
  when: ((pool.name|d()) and (pool.state|d('active') not in [ 'undefined', 'absent' ]))

- name: Certificar que o pool est치 definido
  virt_pool:
    name: "{{ pool.name }}"
    command: define
    xml: '{{ lookup("template", "pool/" + pool.type + ".xml.j2") }}'
  when: ((pool.name|d()) and (pool.state|d('active') not in [ 'undefined', 'absent' ]))

- name: Certificar que o pool est치 ativo
  virt_pool:
    name: "{{ pool.name }}"
    state: active

- name: Certificar que a pool ser치 iniciado no boot
  virt_pool:
    name: "{{ pool.name }}"
    autostart: yes

